### ISSUE TITLE
Fix typo: processing -> possessing party

### ISSUE THREAD

**Issue by RalphTro** [openepcis/epcis-testdata-generator#29]
Dear @Aravinda93,
 
Just a small thing: In the modal for specifying source/destination on https://test-data-generator.openepcis.io/ui/DesignTestData, the tool displays "processing party". It should be "possessing party" though. 

<img width="447" alt="image" src="https://github.com/openepcis/epcis-testdata-generator/assets/46958354/7b0abd06-f0b8-444f-b77e-686d43ced81b">

Thanks in advace for fixing this. 

Kind regards,
@RalphTro

**Comment by Aravinda93** [comment]
Hi @RalphTro 

I apologize for the delayed response. Since I was on vacation, did not get a chance to check the created issues.

I have started looking into the issues created by you and I will fix them one by one and update you on the progress. I have fixed the type issue in the feature branch [feature/OEPCIS-654_fix_issues_based_on_testing](https://github.com/openepcis/epcis-testdata-generator/tree/feature/OEPCIS-654_fix_issues_based_on_testing).
