### ISSUE TITLE
Selection of source/dstination types 

### ISSUE THREAD

**Issue by RalphTro** [openepcis/epcis-testdata-generator#30]
Dear @Aravinda93, 

I just came accross sth. which currently does not seem to work anymore: when trying to specify a source/destination identifier, and having provided all information from my POV, the tool throws a message indicating that I need to select an element from the list (possessing party/owning party/ location). However, I already selected one, and cannot proceed. 

<img width="475" alt="selectSDType" src="https://github.com/openepcis/epcis-testdata-generator/assets/46958354/7c4cd271-0c37-4cfa-9617-6cdb6e6ad836">

Woudl you mind having a look into this matter? 

Many thanks in advance and kind regards,
@RalphTro

**Comment by Aravinda93** [comment]
Dear @RalphTro 

The issue occurred due to a problem with a variable utilized for managing the modal's open/close state. We have fixed the problem and tested the modifications, which appear to be functioning correctly now.

The changes have been committed to a feature branch and will be incorporated into the main branch once the merge process is completed.

**Comment by RalphTro** [comment]
Dear @Aravinda93 ,
Great - and thanks for keeping me up to date! 
Kind regards,
Ralph
