### ISSUE TITLE
 Issue Generating EPICS Aggregation Events with GTDIs

### ISSUE THREAD

**Issue by m4rcs** [openepcis/epcis-testdata-generator#43]
I encountered issues while attempting to generate EPICS Aggregation Events using GTDIs. Specifically, there are errors
in handling GTDIs and during the event generation process.

### Steps to Reproduce:

1. In the Event Data Generator, I used the GTDI `urn:epc:id:gdti:9521141.12345.400` from GS1 TDS (referenced at
   Line 1307) to generate an Aggregation Event.
1. Under _WHAT -> Parent ID_ add the GTDI via the _Add Instance Identifier_ Popup.
1. The Popup displays the following error: **GDTI must be of 13 digits**.
   ![image](https://github.com/openepcis/epcis-testdata-generator/assets/1042745/09761e1e-0230-4aa2-a00a-bfa9de826492)
1. I then entered the same GTDI manually through the _Enter a URI Manually_ option, where it was accepted as a
   ParentID.
1. Upon attempting to generate the event, I received the following error:
   ```
   Error occurred during the deserialization of JSON InputTemplate, Please check the provided InputTemplate : Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
   at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.openepcis.testdata.generator.template.InputTemplate["events"]->java.util.ArrayList[0]->io.openepcis.testdata.generator.template.AggregationEventType["parentIdentifier"])
   ```

Is this a Bug or am I using GTDIs wrong in this Generator? 

Thanks,
Marc

**Comment by Aravinda93** [comment]
@m4rcs Thank you for reaching out to us for clarification.

We are checking the issue seems to have some issue when generating the inputTemplate, we will fix and provide you with confirmation.

**Comment by Aravinda93** [comment]
@m4rcs 

Upon some further investigation, we found that this was happening due to some unwanted object being appended to the generated inputTemplate. We have removed it and the issue seems to be fixed, the changes will be available during the next deployment in production.

However, we also observed that the information you are providing to the GDTI is a bit wrong. You need to provide the 13-digit GDTI in the field something like this: `9521141123454` then based on the provided information the code will generate the GDTI accordingly: `urn:epc:id:gdti:9521141.12345.400`.

Attaching the screenshot and generated event for your reference:

<img width="602" alt="Screenshot 2024-04-15 at 17 57 23" src="https://github.com/openepcis/epcis-testdata-generator/assets/29374160/545a179d-e248-4de4-98b1-9fc0a74aafa3">


Generated event:
```json
{
    "@context": [
        "https://ref.gs1.org/standards/epcis/2.0.0/epcis-context.jsonld"
    ],
    "type": "EPCISDocument",
    "schemaVersion": "2.0",
    "creationDate": "2024-04-15T17:58:25.22Z",
    "epcisBody": {
        "eventList": [
            {
                "type": "AggregationEvent",
                "eventTime": "2024-04-15T17:58:06+02:00",
                "eventTimeZoneOffset": "+02:00",
                "parentID": "https://id.gs1.org/253/9521141123494400",
                "action": "ADD"
            }
        ]
    }
}
```

**Comment by sboeckelmann** [comment]
Dear @m4rcs,

I just deployed the latest version 0.9.3 to https://test-data-generator.openepcis.io/ and it's working now.
For your reference I have exported my settings to the files below, you can upload them into  the create event data tool:
https://test-data-generator.openepcis.io/ui/create-event-data
<img width="247" alt="img06" src="https://github.com/openepcis/epcis-testdata-generator/assets/20949582/710edf2e-4754-4f01-b9da-a2ec9361a219">

please also be aware of the following:
An AggregationEvent Action ADD requires **childEPCs** or **childQuantityList**, otherwise it won't validate against the EPCIS 2.0 schema.
Upload this file into our tool for an AggregationEvent with Action ADD:
[Test_Data_Generator_Create_2024-04-1622_39_11.072.json](https://github.com/openepcis/epcis-testdata-generator/files/15003556/Test_Data_Generator_Create_2024-04-1622_39_11.072.json)

I also created another example for an AggregationEvent with Action DELETE, which is valid without providing **childEPCs** or **childQuantityList**. That's most probably not what you are looking for, but it's syntactically valid 😄 :
[Test_Data_Generator_Create_2024-04-1622_43_54.209.json](https://github.com/openepcis/epcis-testdata-generator/files/15003572/Test_Data_Generator_Create_2024-04-1622_43_54.209.json)

This fix has also been applied to the [GS1 EPCIS Sandbox](https://epcis-sandbox.gs1.org/)

**Comment by sboeckelmann** [comment]
closed after running on [GS1 EPCIS Sandbox](https://epcis-sandbox.gs1.org/)
